Czech translations
michail-nikolaev/task-force-arma-3-radio pull request #1547
Opened 2022-05-04 19:05 UTC by YetheSamartaka

- added all missing Czech Translations
- resolved issue with Turkish duplicity(core.xml)

2022-05-29 00:54 UTC, ilbinek commented
Thank you for the translations. This will certainly make using the addon way easier for Czechs and Slovaks who are not skilled in English.
There are a "few" typos/duplicates and suggestions, which I would be happy if you could take a look at.
Mainly the "SR" - "KV" and "LR" - "DV" ones.

And one last thing, "intercom" could be replaced with the Czech version "interkom".

Translating is hard and takes a lot of time, a lot of mistakes get through because your brain starts to ignore them the more you read the text. There's a high chance I missed some too, so I encourage others to give it another look.

2022-05-29 11:22 UTC, YetheSamartaka commented
> 

Thank you for pointing it out, I will take a look at it this upcoming week.

2022-06-06 18:53 UTC, YetheSamartaka commented
> SR

I have changed the intercom, SR and KV to fit the Czech language better. Is there anything else I should take a look at?

2022-06-06 19:00 UTC, ilbinek requested changes
Oh, I forgot to submit the review. My bad.
There are a few other things I found.

2022-06-09 18:26 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +                <Czech>TFAR-zastaralé</Czech>
Instead I removed the "-" to better fit Czech grammar.

2022-06-09 18:28 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +                <Czech>TFAR – Nastavení na straně klienta</Czech>
Although my version is longer, it gives a more accurate translation of what that setting does.

2022-06-09 18:31 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +                <Czech>Slyšet hlasy z kamery kurátory, když jste v rozhraní Dia</Czech>
That was just a typo. Fixed.

2022-06-09 18:34 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +                <Czech>Žádný automatický pohyb v režimu diváka</Czech>
"Automaticky" is quite a keyword in this case, so I will leave it included there.

2022-06-09 18:38 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +                <Czech>Výchozí rádi střelce (CSAT)</Czech>
Typo. Fixed.

2022-06-09 18:40 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +                <Czech>Zakáže automatické ztlumení ztlumení hráčů v Teamspeaku. (vysoce náročné na výkon)</Czech>
Fixed.

2022-06-09 18:41 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +                <Czech>Zvýšit headset</Czech>
Improved.

2022-06-09 18:41 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +                <Czech>Zvýšit/snížit headset</Czech>
Improved.

2022-06-09 18:41 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +            <Czech>TFAR - nelze kopírovat ze SR do LR</Czech>
Fixed.

2022-06-09 18:42 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +                <Czech>Snížit headset</Czech>
Fixed.

2022-06-09 18:45 UTC, YetheSamartaka commented on addons/external_intercom/stringtable.xml
> +			<Czech><br /><br /><t align='center'>%1 is momentálně používá telefon intercomu</t></Czech>
Fixed.

2022-06-09 18:46 UTC, YetheSamartaka commented on addons/external_intercom/stringtable.xml
> +            <Czech>Dát pryč intercom telefon</Czech>
Agreed.

2022-06-09 18:48 UTC, YetheSamartaka commented on addons/external_intercom/stringtable.xml
> +                <Czech>Další vybavení compatibilní s bezdrátem</Czech>
Improved.

2022-06-09 18:48 UTC, YetheSamartaka commented on addons/external_intercom/stringtable.xml
> +                <Czech>Seznam vybavení, které rozšíří základní seznam vybavení schopnýchse bezdrátově připojit k intercomu vozidla</Czech>
Fixed.

2022-06-09 18:49 UTC, YetheSamartaka commented on addons/external_intercom/stringtable.xml
> +			<Czech><br /><br /><t align='center'>Your %1 není schopno bezdrátového spojení</t></Czech>
Fixed.

2022-06-09 18:50 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +                <Czech>Výchozí SR frekvence:</Czech>
Indeed.

2022-06-09 18:53 UTC, YetheSamartaka commented on addons/core/stringtable.xml
> +                <Czech>tangentReleaseDelay v milisekundách</Czech>
Copy that.

2022-06-09 18:54 UTC, YetheSamartaka commented on addons/handhelds/stringtable.xml
> +            <Czech>AN/PRC-148 JEM  Osobní rádio 5km</Czech>
Fixed.

2022-06-09 18:55 UTC, YetheSamartaka commented on addons/handhelds/stringtable.xml
> +            <Czech>AN/PRC-152  Osobní rádio 5km</Czech>
Fixed.

2022-06-09 18:59 UTC, YetheSamartaka commented
> 

I've gone through all you've suggested, improved and fixed everything. Thank you for reading it all through and pointing out things to fix/improve.

2022-08-06 03:34 UTC, ilbinek approved these changes
A little necro, but all looks good to me.

2022-10-27 09:14 UTC, dedmen commented
Thank you for the reviewing, I don't have the time 😢

2022-10-27 09:14 UTC, merged